os:
  - linux

language:
  - minimal

services:
  - docker

# Container setup.
before_install:
  - |
    docker build -t perl6-ci - <<EOF
      FROM jjmerelo/test-perl6
      RUN apk add --no-cache bash
      # skip here-document terminator due to Travis silliness; produces a warning
  - docker images

# Environment setup.
install:
  # download pds-companion
  - wget -O pds-companion.zip https://github.com/moretrim/pds-companion/archive/0.2.0-alpha+20191122.zip
  - unzip pds-companion.zip

matrix:
  include:
    -
      if: type = pull_request
      name: "Merge Check"
      script: |
        docker run -t                        \
          --name container-env               \
          --env TRAVIS_COMMIT_RANGE          \
          --volume "$TRAVIS_BUILD_DIR":/test \
          --entrypoint bash                  \
          perl6-ci -c '
            # fail on first error
            set -Eeuo pipefail

            # compute difference
            readarray -d "" pr_files < <(git diff --name-only -z --diff-filter=AM "$TRAVIS_COMMIT_RANGE" -- PFH/)
            if (( "${#pr_files[@]}" == 0 )) ; then
              echo "No mod files to test."
              exit
            fi

            # install optional requirement for colour
            zef install --/test Terminal::ANSIColor

            # install pds-companion
            pushd pds-companion-*
            zef install --/test .
            popd

            echo   "## PR: fresh mod files ##"
            printf "    %q\n" "${pr_files[@]}"

            # run static analysis
            vic2-companion --color=always --heartbeat --whitelist --remarks=opinion --base=PFH "${pr_files[@]/PFH\//}"
          '

    -
      if: type = push
      name: "Commit Check"
      script: |
        docker run -t                        \
          --name container-env               \
          --volume "$TRAVIS_BUILD_DIR":/test \
          --entrypoint bash                  \
          perl6-ci -c '
            # fail on first error
            set -Eeuo pipefail

            # compute difference
            readarray -d "" commit_files < <(git diff --name-only -z --diff-filter=AM @^ -- PFH/)
            if (( "${#commit_files[@]}" == 0 )) ; then
              echo "No mod files to test."
              exit
            fi

            # install optional requirement for colour
            zef install --/test Terminal::ANSIColor

            # install pds-companion
            pushd pds-companion-*
            zef install --/test .
            popd

            echo   "## Commit: fresh mod files ##"
            printf "    %q\n" "${commit_files[@]}"

            # run static analysis
            vic2-companion --color=always --heartbeat --whitelist --remarks=opinion --base=PFH "${commit_files[@]/PFH\//}"
          '

    -
      if: type = push
      name: "Branch Check"
      script: |
        docker run -t                        \
          --name container-env               \
          --volume "$TRAVIS_BUILD_DIR":/test \
          --entrypoint bash                  \
          perl6-ci -c '
            # fail on first error
            set -Eeuo pipefail

            # install optional requirement for colour
            zef install --/test Terminal::ANSIColor

            # install pds-companion
            pushd pds-companion-*
            zef install --/test .
            popd

            # run static analysis
            vic2-companion --color=always --heartbeat --whitelist --base=PFH .
          '
